### ISSUE TITLE
Add IV API in CBC mode so IV can be set

### ISSUE THREAD

**Issue by jeroenooms** [s-u/PKI#16]
OpenSSL defaults to an all zero initialization vector. See section titled ***Attacks on CBC mode with predictable IVs*** in [crypto101](https://www.crypto101.io/) for potential concerns.

**Comment by s-u** [comment]
I'm not sure I follow - the AES encryption is precisely defined with a zero IV such that it is a "true" AES encryption. If you changed the IV you couldn't decrypt it anymore as the result would change - making it essentially useless.

Since the API doesn't actually allow you to encrypt whole chains nor set the IV I really have no idea what  this issue is about - it doesn't make sense. Did you mean to suggest that API for IVs to be added to PKI? Or that you could use CBC chains?

**Comment by jeroenooms** [comment]
I ended up completely rewriting the openssl bindings. The `openssl` package defaults to a random IV:

```r
# aes-256 requires 32 byte key
passphrase <- charToRaw("This is super secret")
key <- sha256(passphrase)

# symmetric encryption uses same key for decryption
x <- serialize(iris, NULL)
y <- aes_cbc_encrypt(x, key = key)
x2 <- aes_cbc_decrypt(y, key = key)
stopifnot(identical(x, x2))
```

**Comment by jeroenooms** [comment]
AFAIK, real world applications should use a random IV and store/communicate this along with the ciphertext. The IV is not confidential, but should be random.

**Comment by s-u** [comment]
That depends on the application - yours seems very special, so far I have not seen any application that you use single-block CBC and require IV set. Your comment about insecurity only applies to insecure use. But if you randomize IV by default it breaks any kind of symmetric use so that's certainly not a good idea. I suppose I'm hearing a request for IV API so that applications that do want to set IV can use it.

**Comment by jeroenooms** [comment]
Most applications that I have seen use a random IV. For example openssl's high-level [envelope API](https://wiki.openssl.org/index.php/EVP_Asymmetric_Encryption_and_Decryption_of_an_Envelope):

```c

	/* Initialise the envelope seal operation. This operation generates
	 * a key for the provided cipher, and then encrypts that key a number
	 * of times (one for each public key provided in the pub_key array). In
	 * this example the array size is just one. This operation also
	 * generates an IV and places it in iv. */
```

Anyway I'm not an expert. In `openssl` we use a random `IV` which gets stored as an attribute on the ciphertext. Using `iv = NULL` results in the same output as PKI.

**Comment by jeroenooms** [comment]
I think the main concern is whether or not the application is reusing a key. For randomly generated single-use keys, the iv might not be required. But if a particular key is being reused to encrypt multiple messages, you need to randomize the cipher with an iv.

**Comment by s-u** [comment]
... or use a protocol that incorporates random nonce (as most modern ones do) so you cannot force it to send predictable content. I'll keep this open as a wish for IV API.
